spring:
    application:
        name: proyecto_spring_personal
    output:
        ansi:
            enabled: ALWAYS

server:
    port: 8080
    servlet:
        context-path: /api/v1/todoapp
logging:
    level:
        root: INFO
        org:
            springframework: INFO